/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.9.0 (NJsonSchema v10.6.8.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
// @ts-nocheck

import { AxiosManager, throwException, formatDateWithoutZone, isNullOrUndefinedOrEmpty } from 'utilities'

import axios, { AxiosError, AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

export class AutoGeneratedModels {

    public fullFormSearchCriteria?: FullFormSearchCriteria = null;
	
    constructor(data?: Partial<AutoGeneratedModels>) {
        Object.assign(this, data);
    }
}

export enum Colors {
    Blue = "Blue",
    Green = "Green",
    Red = "Red",
    Yellow = "Yellow",
}

export class FifthLevel {

    public fifthLevelText?: string | null = null;
	
    constructor(data?: Partial<FifthLevel>) {
        Object.assign(this, data);
    }
}

export class FirstLevel {

    public firstLevelText?: string | null = null;
	
    public secondLevel?: SecondLevel = null;
	
    constructor(data?: Partial<FirstLevel>) {
        Object.assign(this, data);
    }
}

export class FourthLevel {

    public fourthLevelText?: string | null = null;
	
    public fifthLevel?: FifthLevel = null;
	
    constructor(data?: Partial<FourthLevel>) {
        Object.assign(this, data);
    }
}

export class FullForm {

    public formName?: string | null = null;
	
    public owner?: Person = null;
	
    public users?: Person[] | null = null;
	
    public multiLevelModel?: MultiLevelModel = null;
	
    constructor(data?: Partial<FullForm>) {
        Object.assign(this, data);
    }
}

export class FullFormSearchCriteria {

    public formName?: string | null = null;
	
    constructor(data?: Partial<FullFormSearchCriteria>) {
        Object.assign(this, data);
    }
}

export enum Gender {
    Male = "Male",
    Female = "Female",
}

export class MultiLevelModel {

    public firstLevel?: FirstLevel = null;
	
    constructor(data?: Partial<MultiLevelModel>) {
        Object.assign(this, data);
    }
}

export class Person {

    public firstName?: string | null = null;
	
    public familyName?: string | null = null;
	
    private _birthDate?: Date | null = null;

    public set birthDate(val: any) {
        this._birthDate = val && typeof val === "string" ? new Date(val) : val
    }
	
    public get birthDate(): Date {
        return this._birthDate;
    }
	
    private _fromDate?: Date | null = null;

    public set fromDate(val: any) {
        this._fromDate = val && typeof val === "string" ? new Date(val) : val
    }
	
    public get fromDate(): Date {
        return this._fromDate;
    }
	
    private _toDate?: Date | null = null;

    public set toDate(val: any) {
        this._toDate = val && typeof val === "string" ? new Date(val) : val
    }
	
    public get toDate(): Date {
        return this._toDate;
    }
	
    public address?: string | null = null;
	
    public favoriteColors?: Colors[] | null = null;
	
    public gender?: Gender = null;
	
    constructor(data?: Partial<Person>) {
        Object.assign(this, data);
        Object.defineProperties(this, {
            _birthDate: { writable: true, enumerable: false },
            birthDate: {
                get: () => { return this._birthDate; },
                set: (val) => { this._birthDate = val && typeof val === "string" ? new Date(val) : val; },
                enumerable: true
            }
        });
        Object.defineProperties(this, {
            _fromDate: { writable: true, enumerable: false },
            fromDate: {
                get: () => { return this._fromDate; },
                set: (val) => { this._fromDate = val && typeof val === "string" ? new Date(val) : val; },
                enumerable: true
            }
        });
        Object.defineProperties(this, {
            _toDate: { writable: true, enumerable: false },
            toDate: {
                get: () => { return this._toDate; },
                set: (val) => { this._toDate = val && typeof val === "string" ? new Date(val) : val; },
                enumerable: true
            }
        });
    }
}

export class SecondLevel {

    public secondLevelText?: string | null = null;
	
    public thirdLevel?: ThirdLevel = null;
	
    constructor(data?: Partial<SecondLevel>) {
        Object.assign(this, data);
    }
}

export class ThirdLevel {

    public thirdLevelText?: string | null = null;
	
    public fourthLevel?: FourthLevel = null;
	
    constructor(data?: Partial<ThirdLevel>) {
        Object.assign(this, data);
    }
}

export class AutoGeneratedModelsClient {
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string) {

        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "/Web.API";

    }

    public get typeDef_AutoGeneratedModelsKey(){
        return "AutoGeneratedModelsClient/TypeDef_AutoGeneratedModels";
    }

    /**
     * @return Success
     */
    typeDef_AutoGeneratedModels(  cancelToken?: CancelToken | undefined): Promise<ApiResponse<AutoGeneratedModels>> {
        let url_ = this.baseUrl + "/TypeDef_AutoGeneratedModels";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        const limiterToken = sessionStorage.getItem("x-contextlimiter-token")

        if (limiterToken)
            options_.headers["x-contextlimiter-token"] = limiterToken;
		
		        return AxiosManager.instance.request(options_).then((_response: AxiosResponse) => {
            return this.processTypeDef_AutoGeneratedModels(_response);
        });
    }

    protected processTypeDef_AutoGeneratedModels(response: AxiosResponse): Promise<ApiResponse<AutoGeneratedModels>> {
        const status = response.status;
        let _headers: any = {};

        if (response.headers && typeof response.headers === "object") {

            const limiterToken = response.headers["x-contextlimiter-token"]

            if (limiterToken){
                sessionStorage.setItem("x-contextlimiter-token", limiterToken);
            }
                
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = new AutoGeneratedModels(resultData200);
            return Promise.resolve<ApiResponse<AutoGeneratedModels>>(new ApiResponse<AutoGeneratedModels>(status, _headers, result200));

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<AutoGeneratedModels>>(new ApiResponse(status, _headers, null as any));
    }
}

export class FullFormClient {
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string) {

        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "/Web.API";

    }

    public get fullFormAllKey(){
        return "FullFormClient/api/FullForm";
    }

    /**
     * @param formName (optional) 
     * @return Success
     */
    fullFormAll(formName: string | undefined , cancelToken?: CancelToken | undefined): Promise<ApiResponse<FullForm[]>> {
        let url_ = this.baseUrl + "/api/FullForm?";
        if (formName === null){
        }else if (formName !== undefined)
            url_ += "FormName=" + encodeURIComponent("" + formName) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        const limiterToken = sessionStorage.getItem("x-contextlimiter-token")

        if (limiterToken)
            options_.headers["x-contextlimiter-token"] = limiterToken;
		
		        return AxiosManager.instance.request(options_).then((_response: AxiosResponse) => {
            return this.processFullFormAll(_response);
        });
    }

    protected processFullFormAll(response: AxiosResponse): Promise<ApiResponse<FullForm[]>> {
        const status = response.status;
        let _headers: any = {};

        if (response.headers && typeof response.headers === "object") {

            const limiterToken = response.headers["x-contextlimiter-token"]

            if (limiterToken){
                sessionStorage.setItem("x-contextlimiter-token", limiterToken);
            }
                
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(new FullForm(item));
            }
            else {
                result200 = <any>null;
            }
            return Promise.resolve<ApiResponse<FullForm[]>>(new ApiResponse<FullForm[]>(status, _headers, result200));

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<FullForm[]>>(new ApiResponse(status, _headers, null as any));
    }

    public get fullFormKey(){
        return "FullFormClient/api/FullForm";
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    fullForm(body: FullForm | undefined , cancelToken?: CancelToken | undefined): Promise<ApiResponse<FullForm>> {
        let url_ = this.baseUrl + "/api/FullForm";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body, (k,v)=> isNullOrUndefinedOrEmpty(v) ? undefined : v);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        const limiterToken = sessionStorage.getItem("x-contextlimiter-token")

        if (limiterToken)
            options_.headers["x-contextlimiter-token"] = limiterToken;
		
		        return AxiosManager.instance.request(options_).then((_response: AxiosResponse) => {
            return this.processFullForm(_response);
        });
    }

    protected processFullForm(response: AxiosResponse): Promise<ApiResponse<FullForm>> {
        const status = response.status;
        let _headers: any = {};

        if (response.headers && typeof response.headers === "object") {

            const limiterToken = response.headers["x-contextlimiter-token"]

            if (limiterToken){
                sessionStorage.setItem("x-contextlimiter-token", limiterToken);
            }
                
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = new FullForm(resultData200);
            return Promise.resolve<ApiResponse<FullForm>>(new ApiResponse<FullForm>(status, _headers, result200));

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ApiResponse<FullForm>>(new ApiResponse(status, _headers, null as any));
    }
}

export class ApiResponse<TResult> {
    status: number;
    headers: { [key: string]: any; };
    result: TResult;

    constructor(status: number, headers: { [key: string]: any; }, result: TResult)
    {
        this.status = status;
        this.headers = headers;
        this.result = result;
    }
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

