using Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Web.API.Controllers
{
    internal sealed class AutoGeneratedModels
    {
        public FullFormSearchCriteria FullFormSearchCriteria { get; set; }
    }

    [AllowAnonymous]
    [Produces("application/json")]
    public class AutoGeneratedModelsController : Controller
    {
        /// <summary>
        /// Описание на метод за добавяне на модели в конфигурацията на Swagger-a, за да бъдат изгенерирани от nswag студиото.
        /// </summary>
        /// <returns></returns>
        [Route("TypeDef_AutoGeneratedModels"), HttpGet, ProducesResponseType(typeof(AutoGeneratedModels), StatusCodes.Status200OK)]
        public IActionResult GetAutoGeneratedModels() => Ok(new AutoGeneratedModels());
    }
}